### ISSUE TITLE
Add a tutorial how to set up a cs2 server that works with this

### ISSUE THREAD

**Issue by BOTGrzes** [shobhit-pathak/cs2-rcon-panel#6]

**Comment by shobhit-pathak** [comment]
Hi, thanks for the suggestion!
But any CS2 server with RCON can work with this panel, no plugin is required, and there are plenty of resources available online for hosting a cs2 server

**Comment by BOTGrzes** [comment]
i setup rcon and it doesnt connect

**Comment by shobhit-pathak** [comment]
Reopening this issue. Could you please share more details? Like what issues are you facing, are you getting any error on the panel? Is RCON working on your server?

**Comment by BOTGrzes** [comment]
RCON Isn't working on my server.
This is my server.cfg
```
hostname "test"
rcon_password "pass"
sv_timeout 60
sv_lan 0
sv_setsteamaccount "server key"
```
And the server shortcut is:
`cs2 -dedicated +game_mode 1 +game_type 0 +map de_dust2`
And i can't connect to RCON from the panel and the game

**Comment by rpkaul** [comment]
add -usercon in launch option too

**Comment by shobhit-pathak** [comment]
As mentioned by @rpkaul, you need to add "-usercon" in the launch option for RCON to work
