### ISSUE TITLE
Change logging to HTTP

### ISSUE THREAD

**Issue by Taraman17** [shobhit-pathak/cs2-rcon-panel#8]
I'm not sure that UDP logging will be made available in the new server.

I would suggest to switch to http logging. Since you are already using express in this, it should not pose a big problem .
Basically it just needs a POST endpoint.
Just did that in my own project (https://github.com/Taraman17/nodejs-cs2-api/blob/master/modules/logreceive.js)

**Comment by shobhit-pathak** [comment]
Hey, thanks for the suggestion and linking your project!
I'll definitely go through it and try implementing http logging in my project, it will help me a lot!

**Comment by Taraman17** [comment]
Very welcome.
I found, that our approach using a RESTful Api is quite similar and I took some inspiration from your code.

So I thought I could give something back. ;-)

**Comment by shobhit-pathak** [comment]
Haha thanks a lot!
